import json
from datetime import datetime, timezone
import discord


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Ticket Transcript — {ticket_id}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: #313338; color: #dbdee1; font-family: 'Whitney', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; }}
  .header {{ background: #1e1f22; padding: 24px 32px; border-bottom: 1px solid #3f4147; }}
  .header h1 {{ font-size: 24px; color: #fff; margin-bottom: 8px; }}
  .header .meta {{ display: flex; gap: 24px; flex-wrap: wrap; }}
  .header .meta-item {{ display: flex; flex-direction: column; gap: 2px; }}
  .header .meta-item .label {{ font-size: 11px; font-weight: 700; text-transform: uppercase; color: #b5bac1; letter-spacing: .5px; }}
  .header .meta-item .value {{ font-size: 14px; color: #dbdee1; }}
  .messages {{ padding: 16px 32px; max-width: 900px; margin: 0 auto; }}
  .message {{ display: flex; gap: 16px; padding: 4px 0; margin-bottom: 4px; }}
  .message:hover {{ background: #2e3035; border-radius: 4px; padding: 4px 8px; margin: 0 -8px 4px; }}
  .avatar {{ width: 40px; height: 40px; border-radius: 50%; flex-shrink: 0; margin-top: 2px; }}
  .msg-body {{ flex: 1; min-width: 0; }}
  .msg-header {{ display: flex; align-items: baseline; gap: 8px; margin-bottom: 4px; }}
  .username {{ font-weight: 600; color: #fff; font-size: 15px; }}
  .timestamp {{ font-size: 12px; color: #87898c; }}
  .content {{ font-size: 15px; line-height: 1.375; word-wrap: break-word; white-space: pre-wrap; color: #dbdee1; }}
  .attachment {{ margin-top: 8px; }}
  .attachment a {{ color: #00aff4; text-decoration: none; }}
  .attachment a:hover {{ text-decoration: underline; }}
  .attachment img {{ max-width: 400px; max-height: 300px; border-radius: 4px; display: block; margin-top: 4px; }}
  .system-msg {{ color: #87898c; font-style: italic; padding: 8px 0; font-size: 14px; border-left: 3px solid #4f545c; padding-left: 12px; margin: 8px 0; }}
  .footer {{ background: #1e1f22; padding: 16px 32px; border-top: 1px solid #3f4147; text-align: center; font-size: 12px; color: #87898c; margin-top: 32px; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 11px; font-weight: 700; text-transform: uppercase; margin-left: 4px; }}
  .badge-open {{ background: #248046; color: #fff; }}
  .badge-closed {{ background: #da373c; color: #fff; }}
</style>
</head>
<body>
<div class="header">
  <h1>🎫 Ticket Transcript — {ticket_id}</h1>
  <div class="meta">
    <div class="meta-item"><span class="label">Category</span><span class="value">{category}</span></div>
    <div class="meta-item"><span class="label">Creator</span><span class="value">{creator}</span></div>
    <div class="meta-item"><span class="label">Opened</span><span class="value">{opened}</span></div>
    <div class="meta-item"><span class="label">Closed</span><span class="value">{closed}</span></div>
    <div class="meta-item"><span class="label">Closed By</span><span class="value">{closer}</span></div>
    <div class="meta-item"><span class="label">Close Reason</span><span class="value">{close_reason}</span></div>
    <div class="meta-item"><span class="label">Messages</span><span class="value">{message_count}</span></div>
  </div>
</div>
<div class="messages">
{messages_html}
</div>
<div class="footer">Generated by Malta SMP Bot &bull; {generated_at}</div>
</body>
</html>"""

MESSAGE_TEMPLATE = """<div class="message">
  <img class="avatar" src="{avatar}" onerror="this.src='https://cdn.discordapp.com/embed/avatars/0.png'" />
  <div class="msg-body">
    <div class="msg-header">
      <span class="username">{username}</span>
      <span class="timestamp">{timestamp}</span>
    </div>
    {content_html}
    {attachments_html}
  </div>
</div>"""


def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def generate_transcript(ticket: dict, messages: list, creator: discord.User | None = None, closer: discord.User | None = None) -> bytes:
    messages_html_parts = []
    for msg in messages:
        content = msg["content"] or ""
        content_html = f'<div class="content">{_escape(content)}</div>' if content else ""

        # Attachments
        attachments = []
        try:
            attachments = json.loads(msg["attachments"]) if msg["attachments"] else []
        except Exception:
            pass

        att_html_parts = []
        for att in attachments:
            url = att.get("url", "")
            filename = att.get("filename", "attachment")
            if any(filename.lower().endswith(ext) for ext in [".png", ".jpg", ".jpeg", ".gif", ".webp"]):
                att_html_parts.append(
                    f'<div class="attachment"><a href="{_escape(url)}">{_escape(filename)}</a>'
                    f'<img src="{_escape(url)}" alt="{_escape(filename)}" /></div>'
                )
            else:
                att_html_parts.append(
                    f'<div class="attachment">📎 <a href="{_escape(url)}">{_escape(filename)}</a></div>'
                )
        attachments_html = "\n".join(att_html_parts)

        # Timestamp
        try:
            ts = datetime.fromisoformat(msg["created_at"])
            ts_str = ts.strftime("%d/%m/%Y %H:%M:%S")
        except Exception:
            ts_str = str(msg["created_at"])

        avatar_url = f"https://cdn.discordapp.com/avatars/{msg['author_id']}/placeholder.png"

        messages_html_parts.append(
            MESSAGE_TEMPLATE.format(
                avatar=avatar_url,
                username=_escape(msg["author_name"] or "Unknown"),
                timestamp=ts_str,
                content_html=content_html,
                attachments_html=attachments_html,
            )
        )

    # Ticket meta
    try:
        opened_dt = datetime.fromisoformat(ticket["created_at"])
        opened_str = opened_dt.strftime("%d/%m/%Y %H:%M:%S UTC")
    except Exception:
        opened_str = str(ticket["created_at"])

    try:
        closed_dt = datetime.fromisoformat(ticket["closed_at"]) if ticket["closed_at"] else None
        closed_str = closed_dt.strftime("%d/%m/%Y %H:%M:%S UTC") if closed_dt else "N/A"
    except Exception:
        closed_str = "N/A"

    creator_str = f"{creator} ({creator.id})" if creator else str(ticket["creator_id"])
    closer_str = f"{closer} ({closer.id})" if closer else (str(ticket["closer_id"]) if ticket["closer_id"] else "N/A")

    html = HTML_TEMPLATE.format(
        ticket_id=_escape(ticket["ticket_id"]),
        category=_escape(ticket["category"]),
        creator=_escape(creator_str),
        opened=opened_str,
        closed=closed_str,
        closer=_escape(closer_str),
        close_reason=_escape(ticket["close_reason"] or "No reason provided"),
        message_count=len(messages),
        messages_html="\n".join(messages_html_parts),
        generated_at=datetime.now(timezone.utc).strftime("%d/%m/%Y %H:%M:%S UTC"),
    )
    return html.encode("utf-8")
